### ISSUE TITLE
plexpass and unraid 6.6.0

### ISSUE THREAD

**Issue by CanonCan** [binhex/arch-plexpass#7]
the latest plexpass docker is pinning CPU's and locking up on unraid 6.6.0 released today wondering if you can take a look

**Comment by CanonCan** [comment]
once cpu is pinned (10min to 1 hour) unraid is locked up to point I cannot mount shares or load plex

**Comment by binhex** [comment]
my advise would be to make this docker container use all cores apart from 'cpu 0' which is the preferred core used by unraid itself, this should prevent plex in essence strangling itself due to cpu starvation.

also keep in mind there was a note by squid about removing cpu pinning prior to upgrading to unraid 6.6.0, i havent made the leap yet but you maybe falling foul of this, see here:-

https://forums.unraid.net/topic/74260-unraid-os-version-660-available/?do=findComment&comment=684116

**Comment by CanonCan** [comment]
i wasnt using extra paramters or pinning all cores are available to the containerlast night cores 2/3 and somtimnes 4 were flipping back and forth to 100% i could not shut the docker down and because ti was stuck i could not shut the unraid array down. i utimately ended up deleting the container and reinstalling it but now the /mnt/user folder keeps messing up so the docker container complains it cant find it and crashes.

**Comment by binhex** [comment]
ok watch out for using /mnt/user for /config, FUSE has a history of causing issues, best bet is to switch the host path to /mnt/cache... instead of /mnt/user/cache, dont know if this is the case for you but thought its worth mentioning.

**Comment by CanonCan** [comment]
Good idea I’ll change it

____________________
Michael

**Comment by CanonCan** [comment]
so i was using /cache for /config its for my Media that it was crashing due to a glitch in unRAID that cause my /user folder to lose all permissions until the server was rebooted
